[dev]
  command = 'yarn start'
  targetPort = 8080
  autoLaunch = true
[build]
  publish = "build"
  functions = 'functions' 
[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs15.x"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200